# Generated by Django 5.0.2 on 2024-02-23 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recognition", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecognizedFace",
        ),
    ]
